module.exports = {
    VERIFY_USER: "VERIFY_USER",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    MESSAGE_SENT: "MESSAGE_SENT",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    LOGOUT: "LOGOUT"
}